# Generated by Django 4.1.1 on 2023-06-22 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
